export const productData = [
  {
    id: "2N10EMLG78CVB",
    description: "Ethnic Motifs Printed Mandarin Collar Tunic And Trousers",
    imageUrls: [
      "https://m.media-amazon.com/images/I/81l1tEk7PBL._SX569_.jpg",
      "https://m.media-amazon.com/images/I/81C+D4gzQ7L._SX569_.jpg",
      "https://m.media-amazon.com/images/I/61D7nbhylBL._SX569_.jpg",
    ],
    category: "Gown",
    brand: "KALINI",
    color: "brown",
    price: 4999,
    gender: "women",
    discountRate: 23,
    size: ["S", "M", "L", "XL"],
    popularity: 3.5,
    trending: true,
    recommended: true,
    feedback: [
      {
        review: 3.2,
        comment: "Color is not so good.",
      },
      {
        review: 3.9,
        comment: "Delivery was a bit late than expected.",
      },
      {
        review: 4.6,
        comment: "Best product ever had.",
      },
    ],
  },
  {
    id: "2N10EMLGHZCVB",
    description: "Ethnic Motifs Printed Mandarin Collar Tunic And Trousers",
    imageUrls: [
      "https://m.media-amazon.com/images/I/61T+3fleIPL._SY741_.jpg",
      "https://m.media-amazon.com/images/I/71WEUQ4is9L._SY741_.jpg",
      "https://m.media-amazon.com/images/I/71y20qz9O8L._SY741_.jpg",
    ],
    category: "top",
    brand: "KALINI",
    color: "black",
    price: 999,
    gender: "women",
    discountRate: 20,
    size: ["S", "M", "L", "XL"],
    popularity: 4.1,
    trending: true,
    recommended: true,
    feedback: [
      {
        review: 3.2,
        comment: "Color is not so good.",
      },
      {
        review: 3.9,
        comment: "Delivery was a bit late than expected.",
      },
      {
        review: 4.6,
        comment: "Best product ever had.",
      },
    ],
  },
  {
    id: "2N10EMLGHZCB",
    description: "GRECIILOOKS Women's Regular Fit Top",
    imageUrls: [
      "https://m.media-amazon.com/images/I/81KpE2l+ehL._SY741_.jpg",
      "https://m.media-amazon.com/images/I/81tMhH-9dAL._SY741_.jpg",
      "https://m.media-amazon.com/images/I/81aBijYyUNL._SY741_.jpg",
    ],
    category: "top",
    brand: "GRECIILOOKS",
    color: "yellow",
    price: 1299,
    gender: "women",
    discountRate: 20,
    size: ["S", "M", "L"],
    popularity: 4.9,
    trending: true,
    recommended: true,
    feedback: [
      {
        review: 3.2,
        comment: "Color is not so good.",
      },
      {
        review: 3.9,
        comment: "Delivery was a bit late than expected.",
      },
      {
        review: 4.6,
        comment: "Best product ever had.",
      },
    ],
  },
  {
    id: "2N10EMLG9ZCB",
    description: "GRECIILOOKS Women's Regular Fit Top",
    imageUrls: [
      "https://m.media-amazon.com/images/I/71r6GM9lu3L._SY741_.jpg",
      "https://m.media-amazon.com/images/I/71pKRYla1cL._SY741_.jpg",
      "https://m.media-amazon.com/images/I/71cOToBehfL._SY741_.jpg",
    ],
    category: "top",
    brand: "GRECIILOOKS",
    color: "white",
    price: 1499,
    gender: "women",
    discountRate: 10,
    size: ["S", "M"],
    popularity: 2.0,
    trending: true,
    recommended: false,
    feedback: [
      {
        review: 3.2,
        comment: "Color is not so good.",
      },
      {
        review: 3.9,
        comment: "Delivery was a bit late than expected.",
      },
      {
        review: 4.6,
        comment: "Best product ever had.",
      },
    ],
  },
  {
    id: "2N10EMLK2ZCB",
    description: "GRECIILOOKS Women's Regular Fit Top",
    imageUrls: [
      "https://m.media-amazon.com/images/I/51d4x7sVvNL.jpg",
      "https://m.media-amazon.com/images/I/51vxc7+scRL.jpg",
      "https://m.media-amazon.com/images/I/51e-ZgZcOTL.jpg",
    ],
    category: "saree",
    brand: "SGF11",
    color: "pink",
    price: 899,
    gender: "women",
    discountRate: 20,
    size: ["M", "L"],
    popularity: 2.9,
    trending: false,
    recommended: true,
    feedback: [
      {
        review: 3.2,
        comment: "Color is not so good.",
      },
      {
        review: 3.9,
        comment: "Delivery was a bit late than expected.",
      },
      {
        review: 4.6,
        comment: "Best product ever had.",
      },
    ],
  },
  {
    id: "2N10EMBQ5ZCB",
    description:
      "Avantika Fashion Women's Kanjivaram Soft Semi Silk Banarasi Sarees With Blouse Piece.",
    imageUrls: [
      "https://m.media-amazon.com/images/I/51F6f5n-2lL.jpg",
      "https://m.media-amazon.com/images/I/61e0dFmr-BL._SX569_.jpg",
      "https://m.media-amazon.com/images/I/71T-i9NhwaL._SX569_.jpg",
    ],
    category: "saree",
    brand: "AVANTIKA FASHION",
    color: "blue",
    price: 2499,
    gender: "women",
    discountRate: 80,
    size: ["M", "L"],
    popularity: 5.0,
    trending: false,
    recommended: true,
    feedback: [
      {
        review: 3.2,
        comment: "Color is not so good.",
      },
      {
        review: 3.9,
        comment: "Delivery was a bit late than expected.",
      },
      {
        review: 4.6,
        comment: "Best product ever had.",
      },
    ],
  },
  {
    id: "2N10E9Q5ZCB",
    description:
      "HELLCAT Trendy Printed Cotton Blend Hoodie T-shirt Jogger Trackpant Clothing Set for Boys ",
    imageUrls: [
      "https://m.media-amazon.com/images/I/51NctJ+OyJL._SY879_.jpg",
      "https://m.media-amazon.com/images/I/61aZQEShb7L._SY741_.jpg",
      "https://m.media-amazon.com/images/I/61UjUeWivNL._SY741_.jpg",
    ],
    category: "Hoodie",
    brand: "HELLCAT",
    color: "blue",
    price: 3998,
    gender: "boy",
    discountRate: 84,
    size: ["M", "L"],
    popularity: 4.0,
    trending: true,
    recommended: true,
    feedback: [
      {
        review: 3.2,
        comment: "Color is not so good.",
      },
      {
        review: 3.9,
        comment: "Delivery was a bit late than expected.",
      },
      {
        review: 4.6,
        comment: "Best product ever had.",
      },
    ],
  },
  {
    id: "2N10E9Q5Z92",
    description:
      "superminis Boy's Cotton Kurta with Dhoti - Golden Thread Work, Round Collar, Full Sleeves, Side Button Kurta Set for Ethnic Wear",
    imageUrls: [
      "https://m.media-amazon.com/images/I/61-F6XFVNVL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/519hL4AKIRL._SX569_.jpg",
      "https://m.media-amazon.com/images/I/519xO1OYBLL._SX569_.jpg",
    ],
    category: "Kurta",
    brand: "Supermini",
    color: "yellow",
    price: 1399,
    gender: "boy",
    discountRate: 61,
    size: ["M", "L"],
    popularity: 4.5,
    trending: false,
    recommended: true,
    feedback: [
      {
        review: 3.2,
        comment: "Color is not so good.",
      },
      {
        review: 3.9,
        comment: "Delivery was a bit late than expected.",
      },
      {
        review: 4.6,
        comment: "Best product ever had.",
      },
    ],
  },
  {
    id: "2N17G9Q5Z92",
    description:
      "Hopscotch Boys Cotton Check Waistcoat Shirt Pant Set in Multi Color",
    imageUrls: [
      "https://m.media-amazon.com/images/I/51p+NkSUtkL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/51hrEi+iR4L._SX679_.jpg",
      "https://m.media-amazon.com/images/I/51iLXAjbx+L._SX679_.jpg",
    ],
    category: "Coat",
    brand: "Hopscotch",
    color: "green",
    price: 1259,
    gender: "boy",
    discountRate: 38,
    size: ["M", "L"],
    popularity: 4.9,
    trending: true,
    recommended: true,
    feedback: [
      {
        review: 3.2,
        comment: "Color is not so good.",
      },
      {
        review: 3.9,
        comment: "Delivery was a bit late than expected.",
      },
      {
        review: 4.6,
        comment: "Best product ever had.",
      },
    ],
  },
  {
    id: "2N17G9Q5P92",
    description:
      "Lymio Men Cargo || Men Cargo Pants || Men Cargo Pants Cotton || Cargos for Men",
    imageUrls: [
      "https://m.media-amazon.com/images/I/51FICIl4KjL._SY741_.jpg",
      "https://m.media-amazon.com/images/I/61FU5-5KPbL._SY741_.jpg",
      "https://m.media-amazon.com/images/I/61cHYeaqqxL._SY741_.jpg",
    ],
    category: "Cargo Pant",
    brand: "Lymio",
    color: "grey",
    price: 4999,
    gender: "men",
    discountRate: 86,
    size: ["M", "L", "XL"],
    popularity: 4.9,
    trending: false,
    recommended: true,
    feedback: [
      {
        review: 3.2,
        comment: "Color is not so good.",
      },
      {
        review: 3.9,
        comment: "Delivery was a bit late than expected.",
      },
      {
        review: 4.6,
        comment: "Best product ever had.",
      },
    ],
  },
  {
    id: "2N17G9Q5P92",
    description: "Bellstone Men's Solid Regular Fit Dress Shirt",
    imageUrls: [
      "https://m.media-amazon.com/images/I/61yWnrT3eQL._SY741_.jpg",
      "https://m.media-amazon.com/images/I/51BeLC7epAL._SX569_.jpg",
      "https://m.media-amazon.com/images/I/61jDfo5TXVL._SX569_.jpg",
    ],
    category: "Shirt",
    brand: "Bellstone",
    color: "grey",
    price: 1499,
    gender: "men",
    discountRate: 71,
    size: ["M", "L", "XL"],
    popularity: 4.6,
    trending: false,
    recommended: true,
    feedback: [
      {
        review: 3.2,
        comment: "Color is not so good.",
      },
      {
        review: 3.9,
        comment: "Delivery was a bit late than expected.",
      },
      {
        review: 4.6,
        comment: "Best product ever had.",
      },
    ],
  },
  {
    id: "2N17APQ5P92",
    description: "Leriya Fashion Men's Regular Fit Shirt",
    imageUrls: [
      "https://m.media-amazon.com/images/I/71ShBw4g6GL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/81GZRfzop6L._SY741_.jpg",
      "https://m.media-amazon.com/images/I/71T5Xo16sVL._SY741_.jpg",
    ],
    category: "Shirt",
    brand: "Leriya",
    color: "blue",
    price: 1999,
    gender: "men",
    discountRate: 83,
    size: ["M", "L", "XL"],
    popularity: 4.6,
    trending: false,
    recommended: true,
    feedback: [
      {
        review: 3.2,
        comment: "Color is not so good.",
      },
      {
        review: 3.9,
        comment: "Delivery was a bit late than expected.",
      },
      {
        review: 4.6,
        comment: "Best product ever had.",
      },
    ],
  },
  {
    id: "2N17AJI1792",
    description: "Fashion Dream Girl's Taffeta Kurta And Pant Suit Sets",
    imageUrls: [
      "https://m.media-amazon.com/images/I/71BbdHIh3kL._SY741_.jpg",
      "https://m.media-amazon.com/images/I/71U9KAYkVgL._SY741_.jpg",
      "https://m.media-amazon.com/images/I/81VWXkteWML._SY741_.jpg",
    ],
    category: "Kurta",
    brand: "Fashion Dream",
    color: "red",
    price: 2299,
    gender: "girls",
    discountRate: 78,
    size: ["M", "L", "XL"],
    popularity: 4.9,
    trending: true,
    recommended: true,
    feedback: [
      {
        review: 3.2,
        comment: "Color is not so good.",
      },
      {
        review: 3.9,
        comment: "Delivery was a bit late than expected.",
      },
      {
        review: 4.6,
        comment: "Best product ever had.",
      },
    ],
  },
  {
    id: "2N17AJI1792",
    description:
      "White Button New latest Girl's Tissue checks readymade Lehenga choli for girls dress",
    imageUrls: ["https://m.media-amazon.com/images/I/61I5WDPSgzL._SX679_.jpg"],
    category: "Lahenga",
    brand: "White Button",
    color: "green",
    price: 1999,
    gender: "girls",
    discountRate: 50,
    size: ["M", "L", "XL"],
    popularity: 4.9,
    trending: false,
    recommended: false,
    feedback: [
      {
        review: 3.2,
        comment: "Color is not so good.",
      },
      {
        review: 3.9,
        comment: "Delivery was a bit late than expected.",
      },
      {
        review: 4.6,
        comment: "Best product ever had.",
      },
    ],
  },
  {
    id: "2N17AJIMM92",
    description:
      "NILKANTHVARNI CREATION Kids Girls Lycra Blend Ready To Wear Saree With Sequence Blouse Piece",
    imageUrls: [
      "https://m.media-amazon.com/images/I/41Vf5mHzLOL._SY679_.jpg",
      "https://m.media-amazon.com/images/I/41hZM6fsIAL._SY679_.jpg",
      "https://m.media-amazon.com/images/I/41KKbVZAofL._SY679_.jpg",
    ],
    category: "saree",
    brand: "Nilkanthvarni Creation",
    color: "pink",
    price: 1499,
    gender: "girls",
    discountRate: 60,
    size: ["M"],
    popularity: 5.0,
    trending: false,
    recommended: true,
    feedback: [
      {
        review: 3.2,
        comment: "Color is not so good.",
      },
      {
        review: 3.9,
        comment: "Delivery was a bit late than expected.",
      },
      {
        review: 4.6,
        comment: "Best product ever had.",
      },
    ],
  },
  {
    id: "2NKIAJIMM92",
    description: "Kuchipoo Girls Full Sleeves Cotton T-Shirt",
    imageUrls: [
      "https://m.media-amazon.com/images/I/71vLWcMlBfL._SX569_.jpg",
      "https://m.media-amazon.com/images/I/61fKDphricL._SX569_.jpg",
      "https://m.media-amazon.com/images/I/61C5VUAPK0L._SX679_.jpg",
    ],
    category: "T-Shirt",
    brand: "Kuchipoo",
    color: "white",
    price: 1999,
    gender: "girls",
    discountRate: 54,
    size: ["M"],
    popularity: 3.8,
    trending: false,
    recommended: true,
    feedback: [
      {
        review: 3.2,
        comment: "Color is not so good.",
      },
      {
        review: 3.9,
        comment: "Delivery was a bit late than expected.",
      },
      {
        review: 4.6,
        comment: "Best product ever had.",
      },
    ],
  },
  {
    id: "2NKMMJIMM92",
    description:
      "GoSriKi Women's Cotton Blend Embroidered Straight Kurta with Pant & Dupatta",
    imageUrls: [
      "https://m.media-amazon.com/images/I/61SgADmAyDL._SY741_.jpg",
      "https://m.media-amazon.com/images/I/61i-0w3GztL._SY741_.jpg",
      "https://m.media-amazon.com/images/I/61ILnUNj20L._SY741_.jpg",
    ],
    category: "Kurta",
    brand: "GoSriKi",
    color: "violet",
    price: 2599,
    gender: "women",
    discountRate: 72,
    size: ["M"],
    popularity: 4.1,
    trending: false,
    recommended: true,
    feedback: [
      {
        review: 3.2,
        comment: "Color is not so good.",
      },
      {
        review: 3.9,
        comment: "Delivery was a bit late than expected.",
      },
      {
        review: 4.6,
        comment: "Best product ever had.",
      },
    ],
  },
  {
    id: "2NKMMJIMM92",
    description:
      "Leriya Fashion Oversized Shirt for Women | Shirt for Women Stylish Western | Women Long Shirt",
    imageUrls: [
      "https://m.media-amazon.com/images/I/71NR4MwqkjL._SY741_.jpg",
      "https://m.media-amazon.com/images/I/71tn9dqDmEL._SY741_.jpg",
      "https://m.media-amazon.com/images/I/71hXzGRQLsL._SY741_.jpg",
    ],
    category: "Shirt",
    brand: "Lehriya Fashion",
    color: "beige",
    price: 1899,
    gender: "women",
    discountRate: 72,
    size: ["M"],
    popularity: 4.5,
    trending: true,
    recommended: true,
    feedback: [
      {
        review: 3.2,
        comment: "Color is not so good.",
      },
      {
        review: 3.9,
        comment: "Delivery was a bit late than expected.",
      },
      {
        review: 4.6,
        comment: "Best product ever had.",
      },
    ],
  },
  {
    id: "2NKMMJIMM92",
    description: "KOTTY Women Polyester Blend Solid Trousers",
    imageUrls: [
      "https://m.media-amazon.com/images/I/51Clvs6gtYL._SY741_.jpg",
      "https://m.media-amazon.com/images/I/51kPUdgTrdL._SY741_.jpg",
      "https://m.media-amazon.com/images/I/51eaHjAB0jL._SY741_.jpg",
    ],
    category: "trouser",
    brand: "KOTTY Store",
    color: "black",
    price: 1899,
    gender: "women",
    discountRate: 87,
    size: ["M", "L", "XL"],
    popularity: 4.5,
    trending: true,
    recommended: true,
    feedback: [
      {
        review: 3.2,
        comment: "Color is not so good.",
      },
      {
        review: 3.9,
        comment: "Delivery was a bit late than expected.",
      },
      {
        review: 4.6,
        comment: "Best product ever had.",
      },
    ],
  },
  {
    id: "2NKMMJIMO92",
    description: "Shasmi Women Maxi Gown",
    imageUrls: [
      "https://m.media-amazon.com/images/I/71GxB8DJLyL._SY741_.jpg",
      "https://m.media-amazon.com/images/I/718utezLE6L._SY741_.jpg",
      "https://m.media-amazon.com/images/I/81r4ArtiQyL._SY741_.jpg",
    ],
    category: "Gown",
    brand: "Shashmi Store",
    color: "blue",
    price: 3499,
    gender: "women",
    discountRate: 67,
    size: ["M", "L", "XL"],
    popularity: 4.5,
    trending: true,
    recommended: true,
    feedback: [
      {
        review: 3.2,
        comment: "Color is not so good.",
      },
      {
        review: 3.9,
        comment: "Delivery was a bit late than expected.",
      },
      {
        review: 4.6,
        comment: "Best product ever had.",
      },
    ],
  },
  {
    id: "2NBQMJIMO92",
    description:
      "BLACKSTEP Women's Cotton Blend T-Shirt & Pyjama Ethnic Co Ord Set, Printed Night Suit, Western Dress, Sleepwear with Relaxed Fit and Stylish Design",
    imageUrls: [
      "https://m.media-amazon.com/images/I/61GZFHGTyiL._SY879_.jpg",
      "https://m.media-amazon.com/images/I/81Tlg0LIHPL._SY741_.jpg",
      "https://m.media-amazon.com/images/I/71d21GEWa-L._SY741_.jpg",
    ],
    category: "Night Suit",
    brand: "Blackstep",
    color: "pink",
    price: 999,
    gender: "women",
    discountRate: 12,
    size: ["M", "L", "XL"],
    popularity: 4.5,
    trending: false,
    recommended: true,
    feedback: [
      {
        review: 3.2,
        comment: "Color is not so good.",
      },
      {
        review: 3.9,
        comment: "Delivery was a bit late than expected.",
      },
      {
        review: 4.6,
        comment: "Best product ever had.",
      },
    ],
  },
  {
    id: "2NBQMJIMO92",
    description: "Istyle Can Plain Round Neck Rib Knit Regular Top for Women",
    imageUrls: [
      "https://m.media-amazon.com/images/I/51LOI3P+sfL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/61H+p5-UjOL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/51P0EvgBcrL._SX679_.jpg",
    ],
    category: "top",
    brand: "Istyle Can",
    color: "pink",
    price: 999,
    gender: "women",
    discountRate: 62,
    size: ["M", "L", "XL"],
    popularity: 4.3,
    trending: false,
    recommended: false,
    feedback: [
      {
        review: 3.2,
        comment: "Color is not so good.",
      },
      {
        review: 3.9,
        comment: "Delivery was a bit late than expected.",
      },
      {
        review: 4.6,
        comment: "Best product ever had.",
      },
    ],
  },
  {
    id: "2NBQMJIMO92",
    description: "GoSriKi Women's Cotton Blend Embroidered Straight Kurta",
    imageUrls: [
      "https://m.media-amazon.com/images/I/51dZ19miAbL._SY741_.jpg",
      "https://m.media-amazon.com/images/I/51yYRttRUFL._SY741_.jpg",
      "https://m.media-amazon.com/images/I/61yTb8brZUL._SY741_.jpg",
    ],
    category: "KURTA",
    brand: "Gosriki",
    color: "white",
    price: 2599,
    gender: "women",
    discountRate: 23,
    size: ["M", "L", "XL"],
    popularity: 4.3,
    trending: false,
    recommended: false,
    feedback: [
      {
        review: 3.2,
        comment: "Color is not so good.",
      },
      {
        review: 3.9,
        comment: "Delivery was a bit late than expected.",
      },
      {
        review: 4.6,
        comment: "Best product ever had.",
      },
    ],
  },
  {
    id: "2NBQMJIMO92",
    description:
      "KOTTY Women's High Rise Viscose Rayon Relaxed Fit Korean Trousers",
    imageUrls: [
      "https://m.media-amazon.com/images/I/61jfBIZmcmL._SY741_.jpg",
      "https://m.media-amazon.com/images/I/611yAQrsWBL._SY741_.jpg",
      "https://m.media-amazon.com/images/I/910PlFIFHwL._SY741_.jpg",
    ],
    category: "trouser",
    brand: "KOTTY",
    color: "white",
    price: 2599,
    gender: "women",
    discountRate: 92,
    size: ["M", "L", "XL"],
    popularity: 4.9,
    trending: false,
    recommended: false,
    feedback: [
      {
        review: 3.2,
        comment: "Color is not so good.",
      },
      {
        review: 3.9,
        comment: "Delivery was a bit late than expected.",
      },
      {
        review: 4.6,
        comment: "Best product ever had.",
      },
    ],
  },
  {
    id: "2NBQMJIMO92",
    description:
      "KOTTY Women's High Rise Viscose Rayon Relaxed Fit Korean Trousers",
    imageUrls: [
      "https://m.media-amazon.com/images/I/61jfBIZmcmL._SY741_.jpg",
      "https://m.media-amazon.com/images/I/611yAQrsWBL._SY741_.jpg",
      "https://m.media-amazon.com/images/I/910PlFIFHwL._SY741_.jpg",
    ],
    category: "trouser",
    brand: "KOTTY",
    color: "white",
    price: 2599,
    gender: "women",
    discountRate: 92,
    size: ["M", "L", "XL"],
    popularity: 4.9,
    trending: false,
    recommended: true,
    feedback: [
      {
        review: 3.2,
        comment: "Color is not so good.",
      },
      {
        review: 3.9,
        comment: "Delivery was a bit late than expected.",
      },
      {
        review: 4.6,
        comment: "Best product ever had.",
      },
    ],
  },
];
